#!/usr/bin/env python3
"""Generate the browser/edge-safe JavaScript entrypoint from the shared core."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages" / "javascript" / "core" / "index.js"
OUTPUT = ROOT / "packages" / "javascript" / "core" / "browser.js"

NODE_IMPORTS = """import fs from \"node:fs\";
import path from \"node:path\";
import { pathToFileURL } from \"node:url\";
"""

BROWSER_STUBS = """// Generated by scripts/build_browser_entrypoint.py. Do not edit directly.
const RUNCOST_BROWSER_RUNTIME = true;
const nodeOnly = (operation) => {
  throw new Error(`${operation} is Node-only. Browser and edge auto-resolution uses an in-memory external price cache.`);
};
const fs = {
  existsSync: () => false,
  mkdirSync: () => nodeOnly(\"filesystem cache creation\"),
  readFileSync: () => nodeOnly(\"filesystem price loading\"),
  readdirSync: () => nodeOnly(\"filesystem cache inspection\"),
  renameSync: () => nodeOnly(\"filesystem cache rename\"),
  unlinkSync: () => nodeOnly(\"filesystem cache deletion\"),
  writeFileSync: () => nodeOnly(\"filesystem cache writing\")
};
const path = {
  dirname: () => nodeOnly(\"filesystem path resolution\"),
  join: () => nodeOnly(\"filesystem path resolution\"),
  resolve: () => nodeOnly(\"filesystem path resolution\")
};
const pathToFileURL = () => nodeOnly(\"filesystem URL conversion\");
"""


def render() -> str:
    source = SOURCE.read_text(encoding="utf-8")
    if not source.startswith(NODE_IMPORTS):
        raise SystemExit("JavaScript core Node import prelude changed; update the browser generator deliberately.")
    return BROWSER_STUBS + source[len(NODE_IMPORTS) :]


def main() -> int:
    expected = render()
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote browser-safe entrypoint to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
