#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
TAXONOMY = ROOT / "schemas" / "taxonomy.json"
PYTHON_OUTPUT = ROOT / "packages" / "python" / "runcost" / "generated" / "taxonomy.py"
PYTHON_INIT = ROOT / "packages" / "python" / "runcost" / "generated" / "__init__.py"
TYPESCRIPT_OUTPUT = ROOT / "packages" / "javascript" / "core" / "generated" / "taxonomy.d.ts"
GO_OUTPUT = ROOT / "packages" / "go" / "ledger" / "generated_taxonomy.go"

ALIASES = {
    "component_names": "UsageComponentName",
    "units": "UsageUnit",
    "warning_codes": "WarningCode",
    "alias_resolution_values": "AliasResolution",
    "debug_decision_types": "DebugDecisionType",
}

CONSTANTS = {
    "component_names": "COMPONENT_NAMES",
    "units": "USAGE_UNITS",
    "warning_codes": "WARNING_CODES",
    "alias_resolution_values": "ALIAS_RESOLUTION_VALUES",
    "debug_decision_types": "DEBUG_DECISION_TYPES",
}


def load_taxonomy() -> dict[str, Any]:
    return json.loads(TAXONOMY.read_text(encoding="utf-8"))


def quoted(value: str) -> str:
    return json.dumps(value)


def python_literal(values: list[str]) -> str:
    if len(values) == 1:
        return f'Literal["{values[0]}"]'
    lines = ["Literal["]
    lines.extend(f"    {quoted(value)}," for value in values)
    lines.append("]")
    return "\n".join(lines)


def generate_python(taxonomy: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/generate_language_types.py --write.",
        "# Do not edit by hand.",
        "from __future__ import annotations",
        "",
        "from typing import Literal",
        "",
    ]
    for key, constant_name in CONSTANTS.items():
        values = taxonomy[key]
        lines.append(f"{constant_name} = (")
        lines.extend(f"    {quoted(value)}," for value in values)
        lines.append(")")
        lines.append("")
    for key, alias_name in ALIASES.items():
        lines.append(f"{alias_name} = {python_literal(taxonomy[key])}")
        lines.append("")
    lines.append("__all__ = [")
    for name in [*CONSTANTS.values(), *ALIASES.values()]:
        lines.append(f"    {quoted(name)},")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def generate_python_init() -> str:
    return (
        "# Generated package for schema-derived RunCost type artifacts.\n"
        "# Individual modules are generated by scripts/generate_language_types.py --write.\n"
    )


def typescript_union(values: list[str]) -> str:
    return "\n".join(f"  | {quoted(value)}" for value in values)


def generate_typescript(taxonomy: dict[str, Any]) -> str:
    lines = [
        "// Generated by scripts/generate_language_types.py --write.",
        "// Do not edit by hand.",
        "",
    ]
    for key, constant_name in CONSTANTS.items():
        values = ", ".join(quoted(value) for value in taxonomy[key])
        lines.append(f"export declare const {constant_name}: readonly [{values}];")
    lines.append("")
    for key, alias_name in ALIASES.items():
        lines.append(f"export type {alias_name} =")
        lines.append(f"{typescript_union(taxonomy[key])};")
        lines.append("")
    return "\n".join(lines)


def go_slice(values: list[str]) -> str:
    lines = ["[]string{"]
    lines.extend(f"\t{quoted(value)}," for value in values)
    lines.append("}")
    return "\n".join(lines)


def generate_go(taxonomy: dict[str, Any]) -> str:
    generated_names = {
        "component_names": "componentOrderNames",
        "units": "usageUnitNames",
        "warning_codes": "warningCodeNames",
        "alias_resolution_values": "aliasResolutionNames",
        "debug_decision_types": "debugDecisionTypeNames",
    }
    lines = [
        "package ledger",
        "",
        "// Generated by scripts/generate_language_types.py --write.",
        "// Do not edit by hand.",
        "",
    ]
    for key, var_name in generated_names.items():
        lines.append(f"var {var_name} = {go_slice(taxonomy[key])}")
        lines.append("")
    return "\n".join(lines)


def expected_outputs() -> dict[Path, str]:
    taxonomy = load_taxonomy()
    return {
        PYTHON_INIT: generate_python_init(),
        PYTHON_OUTPUT: generate_python(taxonomy),
        TYPESCRIPT_OUTPUT: generate_typescript(taxonomy),
        GO_OUTPUT: generate_go(taxonomy),
    }


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, contents in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")
        print(f"Wrote generated language type artifact to {path}")


def check_outputs(outputs: dict[Path, str]) -> None:
    stale = []
    for path, expected in outputs.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    if stale:
        formatted = "\n".join(f"  - {path.relative_to(ROOT)}" for path in stale)
        raise AssertionError(
            "generated language type artifacts are stale; run "
            "`python3 scripts/generate_language_types.py --write`:\n"
            f"{formatted}"
        )
    print("Generated language type artifact checks passed.")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="Write generated language type artifacts.")
    args = parser.parse_args()
    outputs = expected_outputs()
    if args.write:
        write_outputs(outputs)
    else:
        check_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
