#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
TAXONOMY = ROOT / "schemas" / "taxonomy.json"
DEFAULT_OUTPUT = ROOT / "docs" / "generated" / "contract-taxonomy.md"
DEFAULT_SCHEMA_OUTPUT = ROOT / "docs" / "generated" / "schema-fields.md"


def load_taxonomy() -> dict[str, Any]:
    return json.loads(TAXONOMY.read_text(encoding="utf-8"))


def load_schema(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def md_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def bullet_table(values: list[str]) -> list[list[str]]:
    return [[f"`{value}`"] for value in values]


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f"`{schema['$ref']}`"
    value = schema.get("type")
    if isinstance(value, list):
        return ", ".join(f"`{item}`" for item in value)
    if isinstance(value, str):
        return f"`{value}`"
    if "const" in schema:
        return "`const`"
    if "enum" in schema:
        return "`enum`"
    return ""


def schema_constraints(schema: dict[str, Any]) -> str:
    parts: list[str] = []
    if "const" in schema:
        parts.append(f"const `{schema['const']}`")
    if "enum" in schema:
        values = schema["enum"]
        preview = ", ".join(f"`{value}`" for value in values[:8])
        suffix = f" plus {len(values) - 8} more" if len(values) > 8 else ""
        parts.append(f"enum {preview}{suffix}")
    if "default" in schema:
        parts.append(f"default `{json.dumps(schema['default'])}`")
    if "format" in schema:
        parts.append(f"format `{schema['format']}`")
    if "pattern" in schema:
        parts.append(f"pattern `{schema['pattern']}`")
    if "minLength" in schema:
        parts.append(f"minLength `{schema['minLength']}`")
    if "maxLength" in schema:
        parts.append(f"maxLength `{schema['maxLength']}`")
    if "minimum" in schema:
        parts.append(f"minimum `{schema['minimum']}`")
    if "minItems" in schema:
        parts.append(f"minItems `{schema['minItems']}`")
    if "items" in schema:
        parts.append(f"items {schema_type(schema['items'])}".strip())
    if schema.get("additionalProperties") is False:
        parts.append("no extra properties")
    elif schema.get("additionalProperties") is True:
        parts.append("extra properties allowed")
    return md_cell("; ".join(parts))


def generate_taxonomy_docs() -> str:
    taxonomy = load_taxonomy()
    warning_rows = [
        [
            f"`{code}`",
            ", ".join(f"`{key}`" for key in taxonomy["warning_metadata_required_keys"][code]),
        ]
        for code in taxonomy["warning_codes"]
    ]
    lines: list[str] = [
        "---",
        "title: Generated Contract Taxonomy",
        "date: 2026-05-26",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Contract Taxonomy",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `schemas/taxonomy.json`.",
        "Do not edit this file by hand.",
        "",
        f"- Schema version: `{taxonomy['schema_version']}`",
        f"- Status: `{taxonomy['status']}`",
        f"- Locked at: `{taxonomy['locked_at']}`",
        "",
        "## Usage And Price Components",
        "",
        *table(["Component"], bullet_table(taxonomy["component_names"])),
        "",
        "## Units",
        "",
        *table(["Unit"], bullet_table(taxonomy["units"])),
        "",
        "## Warning Codes",
        "",
        *table(["Warning code", "Required metadata keys"], warning_rows),
        "",
        "## Alias Resolution Values",
        "",
        *table(["Alias resolution"], bullet_table(taxonomy["alias_resolution_values"])),
        "",
        "## Fixture Scenarios",
        "",
        *table(["Scenario"], bullet_table(taxonomy["fixture_scenarios"])),
        "",
        "## Expected Languages",
        "",
        *table(["Language"], bullet_table(taxonomy["expected_languages"])),
        "",
        "## Debug Decision Types",
        "",
        *table(["Decision type"], bullet_table(taxonomy["debug_decision_types"])),
        "",
    ]
    return "\n".join(lines)


def schema_object_rows(contract_name: str, object_name: str, schema: dict[str, Any]) -> list[list[str]]:
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    rows: list[list[str]] = []
    for field_name in sorted(properties):
        field_schema = properties[field_name]
        rows.append(
            [
                f"`{contract_name}`",
                f"`{object_name}`",
                f"`{field_name}`",
                "yes" if field_name in required else "no",
                schema_type(field_schema),
                schema_constraints(field_schema),
            ]
        )
    return rows


def generate_schema_docs() -> str:
    schema_paths = sorted(ROOT.glob("schemas/*.schema.json"))
    schema_rows: list[list[str]] = []
    for schema_path in schema_paths:
        schema = load_schema(schema_path)
        contract_name = schema.get("title") or schema_path.stem.removesuffix(".schema")
        schema_rows.extend(schema_object_rows(contract_name, contract_name, schema))
        for def_name, def_schema in sorted(schema.get("$defs", {}).items()):
            if def_schema.get("type") == "object":
                schema_rows.extend(schema_object_rows(contract_name, def_name, def_schema))

    lines: list[str] = [
        "---",
        "title: Generated Schema Fields",
        "date: 2026-05-26",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Schema Fields",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `schemas/*.schema.json`.",
        "Do not edit this file by hand.",
        "",
        *table(
            ["Contract", "Object", "Field", "Required", "Type", "Constraints"],
            schema_rows,
        ),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate taxonomy-derived contract documentation.")
    parser.add_argument("--output", help="Write generated markdown to this path instead of stdout.")
    parser.add_argument("--schema-output", help="Write generated schema-field markdown to this path.")
    parser.add_argument("--write", action="store_true", help="Write to docs/generated/contract-taxonomy.md.")
    args = parser.parse_args()

    taxonomy_content = generate_taxonomy_docs()
    schema_content = generate_schema_docs()
    if args.write:
        DEFAULT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        DEFAULT_OUTPUT.write_text(taxonomy_content, encoding="utf-8")
        DEFAULT_SCHEMA_OUTPUT.write_text(schema_content, encoding="utf-8")
        print(f"Wrote generated contract docs to {DEFAULT_OUTPUT}")
        print(f"Wrote generated schema docs to {DEFAULT_SCHEMA_OUTPUT}")
        return 0
    elif args.output:
        output = Path(args.output)
        content = taxonomy_content
    else:
        print(taxonomy_content, end="")
        if args.schema_output:
            schema_output = Path(args.schema_output)
            schema_output.parent.mkdir(parents=True, exist_ok=True)
            schema_output.write_text(schema_content, encoding="utf-8")
            print(f"\nWrote generated schema docs to {schema_output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote generated contract docs to {output}")
    if args.schema_output:
        schema_output = Path(args.schema_output)
        schema_output.parent.mkdir(parents=True, exist_ok=True)
        schema_output.write_text(schema_content, encoding="utf-8")
        print(f"Wrote generated schema docs to {schema_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
