#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
TAXONOMY = ROOT / "schemas" / "taxonomy.json"
DEFAULT_OUTPUT = ROOT / "docs" / "generated" / "contract-taxonomy.md"
DEFAULT_SCHEMA_OUTPUT = ROOT / "docs" / "generated" / "schema-fields.md"
DEFAULT_SUPPORT_OUTPUT = ROOT / "docs" / "generated" / "fixture-support-matrix.md"
DEFAULT_WARNING_OUTPUT = ROOT / "docs" / "generated" / "warning-coverage.md"
DEFAULT_BETA_OUTPUT = ROOT / "docs" / "generated" / "beta-v1-caveats.md"
DEFAULT_API_OUTPUT = ROOT / "docs" / "generated" / "public-api-registry.md"
COMPLETION_GATES = ROOT / "fixtures" / "source-files" / "project-completion-gates.json"
PUBLIC_API_REGISTRY = ROOT / "fixtures" / "source-files" / "public-api-registry.json"


def load_taxonomy() -> dict[str, Any]:
    return json.loads(TAXONOMY.read_text(encoding="utf-8"))


def load_schema(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_completion_gates() -> dict[str, Any]:
    return json.loads(COMPLETION_GATES.read_text(encoding="utf-8"))


def load_public_api_registry() -> dict[str, Any]:
    return json.loads(PUBLIC_API_REGISTRY.read_text(encoding="utf-8"))


def table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return lines


def md_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def bullet_table(values: list[str]) -> list[list[str]]:
    return [[f"`{value}`"] for value in values]


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f"`{schema['$ref']}`"
    value = schema.get("type")
    if isinstance(value, list):
        return ", ".join(f"`{item}`" for item in value)
    if isinstance(value, str):
        return f"`{value}`"
    if "const" in schema:
        return "`const`"
    if "enum" in schema:
        return "`enum`"
    return ""


def schema_constraints(schema: dict[str, Any]) -> str:
    parts: list[str] = []
    if "const" in schema:
        parts.append(f"const `{schema['const']}`")
    if "enum" in schema:
        values = schema["enum"]
        preview = ", ".join(f"`{value}`" for value in values[:8])
        suffix = f" plus {len(values) - 8} more" if len(values) > 8 else ""
        parts.append(f"enum {preview}{suffix}")
    if "default" in schema:
        parts.append(f"default `{json.dumps(schema['default'])}`")
    if "format" in schema:
        parts.append(f"format `{schema['format']}`")
    if "pattern" in schema:
        parts.append(f"pattern `{schema['pattern']}`")
    if "minLength" in schema:
        parts.append(f"minLength `{schema['minLength']}`")
    if "maxLength" in schema:
        parts.append(f"maxLength `{schema['maxLength']}`")
    if "minimum" in schema:
        parts.append(f"minimum `{schema['minimum']}`")
    if "minItems" in schema:
        parts.append(f"minItems `{schema['minItems']}`")
    if "items" in schema:
        parts.append(f"items {schema_type(schema['items'])}".strip())
    if schema.get("additionalProperties") is False:
        parts.append("no extra properties")
    elif schema.get("additionalProperties") is True:
        parts.append("extra properties allowed")
    return md_cell("; ".join(parts))


def generate_taxonomy_docs() -> str:
    taxonomy = load_taxonomy()
    warning_rows = [
        [
            f"`{code}`",
            ", ".join(f"`{key}`" for key in taxonomy["warning_metadata_required_keys"][code]),
        ]
        for code in taxonomy["warning_codes"]
    ]
    lines: list[str] = [
        "---",
        "title: Generated Contract Taxonomy",
        "date: 2026-05-26",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Contract Taxonomy",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `schemas/taxonomy.json`.",
        "Do not edit this file by hand.",
        "",
        f"- Schema version: `{taxonomy['schema_version']}`",
        f"- Status: `{taxonomy['status']}`",
        f"- Locked at: `{taxonomy['locked_at']}`",
        "",
        "## Usage And Price Components",
        "",
        *table(["Component"], bullet_table(taxonomy["component_names"])),
        "",
        "## Units",
        "",
        *table(["Unit"], bullet_table(taxonomy["units"])),
        "",
        "## Warning Codes",
        "",
        *table(["Warning code", "Required metadata keys"], warning_rows),
        "",
        "## Alias Resolution Values",
        "",
        *table(["Alias resolution"], bullet_table(taxonomy["alias_resolution_values"])),
        "",
        "## Fixture Scenarios",
        "",
        *table(["Scenario"], bullet_table(taxonomy["fixture_scenarios"])),
        "",
        "## Expected Languages",
        "",
        *table(["Language"], bullet_table(taxonomy["expected_languages"])),
        "",
        "## Debug Decision Types",
        "",
        *table(["Decision type"], bullet_table(taxonomy["debug_decision_types"])),
        "",
    ]
    return "\n".join(lines)


def schema_object_rows(contract_name: str, object_name: str, schema: dict[str, Any]) -> list[list[str]]:
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    rows: list[list[str]] = []
    for field_name in sorted(properties):
        field_schema = properties[field_name]
        rows.append(
            [
                f"`{contract_name}`",
                f"`{object_name}`",
                f"`{field_name}`",
                "yes" if field_name in required else "no",
                schema_type(field_schema),
                schema_constraints(field_schema),
            ]
        )
    return rows


def generate_schema_docs() -> str:
    schema_paths = sorted(ROOT.glob("schemas/*.schema.json"))
    schema_rows: list[list[str]] = []
    for schema_path in schema_paths:
        schema = load_schema(schema_path)
        contract_name = schema.get("title") or schema_path.stem.removesuffix(".schema")
        schema_rows.extend(schema_object_rows(contract_name, contract_name, schema))
        for def_name, def_schema in sorted(schema.get("$defs", {}).items()):
            if def_schema.get("type") == "object":
                schema_rows.extend(schema_object_rows(contract_name, def_name, def_schema))

    lines: list[str] = [
        "---",
        "title: Generated Schema Fields",
        "date: 2026-05-26",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Schema Fields",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `schemas/*.schema.json`.",
        "Do not edit this file by hand.",
        "",
        *table(
            ["Contract", "Object", "Field", "Required", "Type", "Constraints"],
            schema_rows,
        ),
        "",
    ]
    return "\n".join(lines)


def fixture_metadata_rows() -> list[list[str]]:
    rows: list[list[str]] = []
    for fixture_path in sorted((ROOT / "fixtures").glob("*.json")):
        fixture = load_schema(fixture_path)
        metadata = fixture.get("metadata", {})
        provider = metadata.get("provider", "")
        surface = metadata.get("surface", "")
        scenario = metadata.get("scenario", "")
        languages = ", ".join(f"`{language}`" for language in metadata.get("expected_languages", []))
        tags = ", ".join(f"`{tag}`" for tag in metadata.get("tags", []))
        rows.append(
            [
                f"`{provider}`",
                f"`{surface}`",
                f"`{scenario}`",
                f"[{fixture_path.name}](../../fixtures/{fixture_path.name})",
                languages,
                tags,
            ]
        )
    return rows


def support_summary_rows(rows: list[list[str]]) -> list[list[str]]:
    by_provider: dict[str, dict[str, set[str] | int]] = {}
    for provider, surface, scenario, _fixture, languages, _tags in rows:
        key = provider.strip("`")
        summary = by_provider.setdefault(
            key,
            {"surfaces": set(), "scenarios": set(), "languages": set(), "fixtures": 0},
        )
        summary["surfaces"].add(surface.strip("`"))  # type: ignore[union-attr]
        summary["scenarios"].add(scenario.strip("`"))  # type: ignore[union-attr]
        for language in languages.replace("`", "").split(", "):
            if language:
                summary["languages"].add(language)  # type: ignore[union-attr]
        summary["fixtures"] = int(summary["fixtures"]) + 1

    summary_rows: list[list[str]] = []
    for provider in sorted(by_provider):
        summary = by_provider[provider]
        summary_rows.append(
            [
                f"`{provider}`",
                str(summary["fixtures"]),
                str(len(summary["surfaces"])),  # type: ignore[arg-type]
                ", ".join(f"`{value}`" for value in sorted(summary["scenarios"])),  # type: ignore[arg-type]
                ", ".join(f"`{value}`" for value in sorted(summary["languages"])),  # type: ignore[arg-type]
            ]
        )
    return summary_rows


def generate_support_docs() -> str:
    rows = fixture_metadata_rows()
    lines: list[str] = [
        "---",
        "title: Generated Fixture Support Matrix",
        "date: 2026-05-26",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Fixture Support Matrix",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `fixtures/*.json` metadata.",
        "Do not edit this file by hand.",
        "",
        f"- Fixture count: `{len(rows)}`",
        "",
        "## Provider Summary",
        "",
        *table(
            ["Provider", "Fixtures", "Surfaces", "Scenarios", "Languages"],
            support_summary_rows(rows),
        ),
        "",
        "## Fixture Matrix",
        "",
        *table(
            ["Provider", "Surface", "Scenario", "Fixture", "Languages", "Tags"],
            rows,
        ),
        "",
    ]
    return "\n".join(lines)


def fixture_warning_codes(fixture: dict[str, Any]) -> set[str]:
    codes: set[str] = set()
    expected = fixture.get("expected", {})
    cost_ledger = expected.get("cost_ledger", {})
    for warning in cost_ledger.get("warnings", []):
        code = warning.get("code")
        if isinstance(code, str):
            codes.add(code)
    error = expected.get("error", {})
    error_code = error.get("code")
    if isinstance(error_code, str):
        codes.add(error_code)
    metadata = fixture.get("metadata", {})
    for tag in metadata.get("tags", []):
        if isinstance(tag, str) and tag.startswith("warning:"):
            codes.add(tag.split(":", 1)[1])
    return codes


def warning_coverage_rows() -> list[list[str]]:
    taxonomy = load_taxonomy()
    by_code: dict[str, list[str]] = {code: [] for code in taxonomy["warning_codes"]}
    for fixture_path in sorted((ROOT / "fixtures").glob("*.json")):
        fixture = load_schema(fixture_path)
        for code in fixture_warning_codes(fixture):
            by_code.setdefault(code, []).append(fixture_path.name)

    rows: list[list[str]] = []
    for code in taxonomy["warning_codes"]:
        fixtures = by_code.get(code, [])
        fixture_links = ", ".join(f"[{name}](../../fixtures/{name})" for name in fixtures)
        rows.append(
            [
                f"`{code}`",
                ", ".join(f"`{key}`" for key in taxonomy["warning_metadata_required_keys"][code]),
                str(len(fixtures)),
                fixture_links or "",
                "fixture-backed" if fixtures else "uncovered",
            ]
        )
    return rows


def generate_warning_docs() -> str:
    rows = warning_coverage_rows()
    uncovered = [row[0] for row in rows if row[4] == "uncovered"]
    lines: list[str] = [
        "---",
        "title: Generated Warning Coverage",
        "date: 2026-05-26",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Warning Coverage",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `schemas/taxonomy.json` and `fixtures/*.json`.",
        "Do not edit this file by hand.",
        "",
        f"- Warning codes: `{len(rows)}`",
        f"- Fixture-backed warning codes: `{len(rows) - len(uncovered)}`",
        f"- Uncovered warning codes: `{len(uncovered)}`",
        "",
        (
            "All warning codes currently have shared fixture coverage."
            if not uncovered
            else "Uncovered warning codes are valid contract values, but they are not yet supported claims. Add a shared fixture before relying on them for V1 behavior."
        ),
        "",
        "## Warning Coverage Matrix",
        "",
        *table(
            ["Warning code", "Required metadata keys", "Fixtures", "Fixture links", "Status"],
            rows,
        ),
        "",
    ]
    return "\n".join(lines)


def generate_beta_caveats_docs() -> str:
    register = load_completion_gates()
    gate_rows: list[list[str]] = []
    incomplete = [gate for gate in register["gates"] if gate["status"] != "satisfied"]
    for gate in incomplete:
        required_for = ", ".join(f"`{value}`" for value in gate["required_for"])
        gate_rows.append(
            [
                f"`{gate['id']}`",
                f"`{gate['area']}`",
                required_for,
                f"`{gate['status']}`",
                md_cell(gate.get("remaining_action") or gate.get("deferred_reason", "")),
            ]
        )

    lines: list[str] = [
        "---",
        "title: Generated Beta And V1 Caveats",
        "date: 2026-05-26",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Beta And V1 Caveats",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `fixtures/source-files/project-completion-gates.json`.",
        "Do not edit this file by hand.",
        "",
        f"- Completion gate register version: `{register['schema_version']}`",
        f"- Register updated at: `{register['updated_at']}`",
        f"- Incomplete gates: `{len(incomplete)}`",
        "",
        "These caveats are public-support claims, not implementation plans. A surface remains pre-beta or pre-V1 until the strict gate commands pass against real evidence.",
        "",
        "## Strict Gate Commands",
        "",
        "```bash",
        "python3 scripts/check_alpha_evidence_bundle.py \\",
        "  --smoke-report <sanitized-live-report.json> \\",
        "  --smoke-report <sanitized-vercel-report.json> \\",
        "  --smoke-report <sanitized-langchain-report.json> \\",
        "  --invoice-comparison <sanitized-real-comparison.json> \\",
        "  --require-real",
        "python3 scripts/check_project_completion_gates.py --require-milestone8",
        "python3 scripts/check_project_completion_gates.py --require-public-beta",
        "python3 scripts/check_project_completion_gates.py --require-v1",
        "```",
        "",
        "## Remaining Caveats",
        "",
        *table(
            ["Gate", "Area", "Required for", "Status", "Remaining action"],
            gate_rows,
        ),
        "",
    ]
    return "\n".join(lines)


def generate_public_api_docs() -> str:
    registry = load_public_api_registry()
    rows: list[list[str]] = []
    for capability in registry["capabilities"]:
        language_cells = []
        for language in ["python", "javascript", "go"]:
            api = capability["languages"][language]
            names = [*api.get("runtime", []), *api.get("types", [])]
            language_cells.append(", ".join(f"`{name}`" for name in names) or "")
        rows.append(
            [
                f"`{capability['id']}`",
                f"`{capability['category']}`",
                f"`{capability['status']}`",
                *language_cells,
            ]
        )

    lines: list[str] = [
        "---",
        "title: Generated Public API Registry",
        "date: 2026-05-27",
        "type: reference",
        "status: generated",
        "---",
        "",
        "# Generated Public API Registry",
        "",
        "Generated by `python3 scripts/generate_contract_docs.py --write` from `fixtures/source-files/public-api-registry.json`.",
        "Do not edit this file by hand.",
        "",
        f"- Registry version: `{registry['schema_version']}`",
        f"- Registry updated at: `{registry['updated_at']}`",
        f"- Capabilities: `{len(registry['capabilities'])}`",
        "",
        "This generated view is the package-surface counterpart to the schema and fixture contracts: it records which runtime functions and type names each supported language must export.",
        "",
        "## API Matrix",
        "",
        *table(["Capability", "Category", "Status", "Python", "JavaScript/TypeScript", "Go"], rows),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate taxonomy-derived contract documentation.")
    parser.add_argument("--output", help="Write generated markdown to this path instead of stdout.")
    parser.add_argument("--schema-output", help="Write generated schema-field markdown to this path.")
    parser.add_argument("--support-output", help="Write generated fixture support matrix markdown to this path.")
    parser.add_argument("--warning-output", help="Write generated warning coverage markdown to this path.")
    parser.add_argument("--beta-output", help="Write generated beta/V1 caveats markdown to this path.")
    parser.add_argument("--api-output", help="Write generated public API registry markdown to this path.")
    parser.add_argument("--write", action="store_true", help="Write to docs/generated/contract-taxonomy.md.")
    args = parser.parse_args()

    taxonomy_content = generate_taxonomy_docs()
    schema_content = generate_schema_docs()
    support_content = generate_support_docs()
    warning_content = generate_warning_docs()
    beta_content = generate_beta_caveats_docs()
    api_content = generate_public_api_docs()
    if args.write:
        DEFAULT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        DEFAULT_OUTPUT.write_text(taxonomy_content, encoding="utf-8")
        DEFAULT_SCHEMA_OUTPUT.write_text(schema_content, encoding="utf-8")
        DEFAULT_SUPPORT_OUTPUT.write_text(support_content, encoding="utf-8")
        DEFAULT_WARNING_OUTPUT.write_text(warning_content, encoding="utf-8")
        DEFAULT_BETA_OUTPUT.write_text(beta_content, encoding="utf-8")
        DEFAULT_API_OUTPUT.write_text(api_content, encoding="utf-8")
        print(f"Wrote generated contract docs to {DEFAULT_OUTPUT}")
        print(f"Wrote generated schema docs to {DEFAULT_SCHEMA_OUTPUT}")
        print(f"Wrote generated support docs to {DEFAULT_SUPPORT_OUTPUT}")
        print(f"Wrote generated warning docs to {DEFAULT_WARNING_OUTPUT}")
        print(f"Wrote generated beta/V1 caveats docs to {DEFAULT_BETA_OUTPUT}")
        print(f"Wrote generated public API docs to {DEFAULT_API_OUTPUT}")
        return 0
    elif args.output:
        output = Path(args.output)
        content = taxonomy_content
    else:
        print(taxonomy_content, end="")
        if args.schema_output:
            schema_output = Path(args.schema_output)
            schema_output.parent.mkdir(parents=True, exist_ok=True)
            schema_output.write_text(schema_content, encoding="utf-8")
            print(f"\nWrote generated schema docs to {schema_output}")
        if args.support_output:
            support_output = Path(args.support_output)
            support_output.parent.mkdir(parents=True, exist_ok=True)
            support_output.write_text(support_content, encoding="utf-8")
            print(f"\nWrote generated support docs to {support_output}")
        if args.warning_output:
            warning_output = Path(args.warning_output)
            warning_output.parent.mkdir(parents=True, exist_ok=True)
            warning_output.write_text(warning_content, encoding="utf-8")
            print(f"\nWrote generated warning docs to {warning_output}")
        if args.beta_output:
            beta_output = Path(args.beta_output)
            beta_output.parent.mkdir(parents=True, exist_ok=True)
            beta_output.write_text(beta_content, encoding="utf-8")
            print(f"\nWrote generated beta/V1 caveats docs to {beta_output}")
        if args.api_output:
            api_output = Path(args.api_output)
            api_output.parent.mkdir(parents=True, exist_ok=True)
            api_output.write_text(api_content, encoding="utf-8")
            print(f"\nWrote generated public API docs to {api_output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote generated contract docs to {output}")
    if args.schema_output:
        schema_output = Path(args.schema_output)
        schema_output.parent.mkdir(parents=True, exist_ok=True)
        schema_output.write_text(schema_content, encoding="utf-8")
        print(f"Wrote generated schema docs to {schema_output}")
    if args.support_output:
        support_output = Path(args.support_output)
        support_output.parent.mkdir(parents=True, exist_ok=True)
        support_output.write_text(support_content, encoding="utf-8")
        print(f"Wrote generated support docs to {support_output}")
    if args.warning_output:
        warning_output = Path(args.warning_output)
        warning_output.parent.mkdir(parents=True, exist_ok=True)
        warning_output.write_text(warning_content, encoding="utf-8")
        print(f"Wrote generated warning docs to {warning_output}")
    if args.beta_output:
        beta_output = Path(args.beta_output)
        beta_output.parent.mkdir(parents=True, exist_ok=True)
        beta_output.write_text(beta_content, encoding="utf-8")
        print(f"Wrote generated beta/V1 caveats docs to {beta_output}")
    if args.api_output:
        api_output = Path(args.api_output)
        api_output.parent.mkdir(parents=True, exist_ok=True)
        api_output.write_text(api_content, encoding="utf-8")
        print(f"Wrote generated public API docs to {api_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
